--- 
 #- include_vars: main.yml
 
 #- name: Download WAR to server
  # synchronize: src=/var/lib/jenkins/workspace/jenkins_assignment/target/JenkinsAssignment.war dest=/opt/bitnami/tomcat/webapps

 - name: Unzip WAR file
   copy:
      src: /var/lib/jenkins/workspace/jenkins_assignment/target/JenkinsAssignment.war 
      dest: /opt/tomcat/webapps/ 
    #  mode: 0755
     # owner: tomcat 
     # group: tomcat
      #remote-src: yes
  # notify:
   #   - Restart tomcat8




























